version: '3.8'

services:
  melo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melo-coffee
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
    volumes:
      - melo_uploads:/app/public/uploads

volumes:
  melo_uploads:
