version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: melo-db-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: melo
    ports:
      - "5435:5432"
    volumes:
      - melo_db_data_local:/var/lib/postgresql/data

volumes:
  melo_db_data_local:
